### ISSUE TITLE
 v1.2.0 no UE 5.2 support?

### ISSUE THREAD

**Issue by Tobe2d** [readyplayerme/rpm-unreal-sdk#25]
I cant find Release-Blueprint  for UE 5.2

![image](https://github.com/readyplayerme/rpm-unreal-sdk/assets/4099839/7ec906eb-2aea-4d19-80af-bc04f5bb422f)

**Comment by gadamyan** [comment]
Thanks for the report. We had an issue with UE5.2. Now it should be there
