### ISSUE TITLE
UE5.3 doesn't build due to missing header "Media/Public/IMediaTracks.h"

### ISSUE THREAD

**Issue by jimsimonz** [readyplayerme/rpm-unreal-sdk#32]
**Describe the bug**
Build fails due to missing header.
The header isn't actually required so can be removed from ReadyPlayerMeComponent.cpp

//#include "Media/Public/IMediaTracks.h"

**Comment by gadamyan** [comment]
Thanks for the info it will be removed in the next release, and will most probably be available next week.

**Comment by jimsimonz** [comment]
great thanks

**Comment by jimsimonz** [comment]
fixed in latest repo
